local plugin = require("tree-emmet")
local str = require("tree-emmet.string")

local source = { "lorem", "ipsum", "yayho" }

describe("trim", function()
  it("must trim", function()
    assert.are_equal("", str.trim("   "))
  end)
end)

describe("remove_range", function()
  it("must remove empty sentences", function()
    local result = str.remove_ranges({ "lorem", "       ", "yayho" }, {})
    assert.are_equal({ "lorem", "yayho" }, result)
  end)
  it("must remove range", function()
    local result = str.remove_ranges(source, { { 1, 1, 1, 3 }, { 2, 2, 2, 3 }, { 3, 4, 3, 5 } })
    assert.are_equal({ "em", "ium", "yay" }, result)
  end)
  it("must remove range", function()
    local result = str.remove_ranges(source, { { 1, 4, 3, 2 } })
    assert.are_equal({ "lor", "", "yho" }, result)
  end)
  it("must remove range", function()
    local result = str.remove_ranges(source, { { 1, 1, 1, 3 }, { 3, 3, 3, 5 } })
    assert.are_equal({ "em", "ipsum", "ya" }, result)
  end)
end)
